# Verwende offizielles Nginx Image
FROM nginx:alpine

# Deine HTML-Dateien ins Standard-Webverzeichnis kopieren
COPY frontend/ /usr/share/nginx/html/

# Optional: eigene nginx.conf einfügen (z.B. für hübsche Logs oder SPA Support)
# COPY nginx.conf /etc/nginx/conf.d/default.conf