version: '3.8'

services:
  discord-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - NODE_ENV=production
    # Für persistente Daten (falls benötigt)
    volumes:
      - ./data:/app/data
    # Leistungsoptimierungen
    mem_limit: 512m
    cpus: 1
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Netzwerk konfigurieren (nicht notwendig, aber gut für Erweiterungen)
networks:
  default:
    name: discord-bot-network