version: '3.8'

services:
  discord-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    mem_limit: 512m
    cpus: 1
    healthcheck:
      disable: true
    networks:
      - botnet

  frontend:
    image: nginx:latest
    container_name: discord-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"
    networks:
      - botnet

networks:
  botnet:
    name: discord-bot-network